# Generated by Django 5.1.1 on 2024-09-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information_title', models.CharField(max_length=100)),
                ('information_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InnovationBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innovation_name', models.CharField(max_length=150)),
                ('innovation_image', models.ImageField(blank=True, upload_to='')),
                ('innovation_file', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='NewsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=100)),
                ('news_content', models.TextField()),
                ('news_image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
