# Generated by Django 5.1.1 on 2024-09-23 10:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_pages', '0002_informationblock_innovationblock_newsblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsblock',
            name='news_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
