# Generated by Django 5.1.1 on 2024-09-23 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_pages', '0004_remove_newsblock_news_image_newsimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsimage',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='other_pages.newsblock'),
        ),
    ]
