# Generated by Django 5.1.1 on 2024-09-17 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessontouser',
            name='completed',
        ),
    ]
