# Generated by Django 5.1.1 on 2024-09-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_lessontouser_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='on_main_page',
            field=models.BooleanField(default=False),
        ),
    ]
