# Generated by Django 5.1.1 on 2024-09-19 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_company_logo_alter_course_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakertocourse',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.speaker'),
        ),
    ]
