# Generated by Django 5.1.1 on 2024-09-20 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_speakertocourse_speaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.company'),
        ),
    ]
