# Generated by Django 5.1.1 on 2024-09-23 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answertotext',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_to_text', to='courses.texttolesson'),
        ),
        migrations.AlterField(
            model_name='lessontouser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_to_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
