# Generated by Django 5.1.1 on 2024-09-18 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_aboutcourse_course_alter_coursetouser_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessontouser',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_to_lesson', to='courses.lesson'),
        ),
        migrations.AlterField(
            model_name='speakertolesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_to_lesson', to='courses.lesson'),
        ),
        migrations.AlterField(
            model_name='texttolesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_to_lesson', to='courses.lesson'),
        ),
        migrations.AlterField(
            model_name='videotolesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_to_lesson', to='courses.lesson'),
        ),
        migrations.AlterUniqueTogether(
            name='speakertocourse',
            unique_together={('speaker', 'course')},
        ),
    ]
